//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguangeSattarov
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }

        public string BirthdayString
        {
            get
            {
                if (Birthday.HasValue)
                {
                    return Birthday.Value.ToShortDateString();
                }
                return "не указана";
            }
        }


        public System.DateTime RegistrationDate { get; set; }
        public string RegistrationDateString
        {
            get
            {
                return RegistrationDate.ToShortDateString();
            }
        }
        public string LastVisitDate
        {
            get
            {
                var LastVisit = ClientService.Where(p => p.ClientID == this.ID).OrderByDescending(p => p.StartTime).FirstOrDefault();
                if (LastVisit == null)
                {
                    return "нет";
                }
                else
                { 
                    DateTime startTime = LastVisit.StartTime;
                    return startTime.ToString("d");
                }
            }
        }
        public DateTime? LastVisitDateTime
        {
            get
            {
                var LastVisit = ClientService.Where(p => p.ClientID==this.ID).OrderByDescending(p=>p.StartTime).FirstOrDefault();
                
                return LastVisit?.StartTime;
            }
        }

        public string GenderName
        {
            get
            {

                return Gender.Name;
            }
        }
        public int VisitCount
        {
            get
            {

                return ClientService.Count(p => p.ClientID == this.ID);
            }
        }



        public string Email { get; set; }
        public string Phone { get; set; }
        public string GenderCode { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
